apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: amina1011/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env: # Add environment variables here
            - name: MONGO_URI
              value: "mongodb+srv://admin:admin@schooldata.ki5zh.mongodb.net/?retryWrites=true&w=majority&appName=schooldata"

---

apiVersion: v1
kind: Service
metadata:
  name: backend-ssvc
spec:
  selector:
    app: backend
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  type: LoadBalancer
